---
- name: Install Hyprland runtime packages
  ansible.builtin.dnf:
    name:
      - hyprland
      - hypridle
      - hyprlock
    state: present
  become: true

- name: Link Hyprland configuration
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../config/hypr"
    dest: "{{ ansible_facts['user_dir'] }}/.config/hypr"
    state: link
    force: true
