---
- name: Install Fedora Quickshell build compatible with Qt 6.11
  ansible.builtin.dnf:
    name: "quickshell-0.2.1^git20260209.dacfa9d-5.fc44"
    state: present
    allow_downgrade: true
    disablerepo:
      - "copr:copr.fedorainfracloud.org:nett00n:hyprland"
  become: true

- name: Link Quickshell configuration
  ansible.builtin.file:
    src: "{{ playbook_dir }}/../shell/quickshell"
    dest: "{{ ansible_facts['user_dir'] }}/.config/quickshell"
    state: link
    force: true
